# Copyright © 2024 Contributors to Project Ocre, which has been established as Project Ocre a Series of LF Projects, LLC.
# Distributed by an Apache 2.0 License.

# Ocre container image definition

version: '1'

name: hello-world 
binaries:
  - path: hello-world.wasm

config:
  environment:
    - Message
  permissions:
    - console